[tool.cibuildwheel]
build = [
    "cp310-*",  # CPython 3.10
    "cp311-*",  # CPython 3.11
    "cp312-*",  # CPython 3.12
    "cp313-*",  # CPython 3.13
    "cp314-*",  # CPython 3.14
    "cp314t-*", # CPython 3.14t (free-threading)
]
build-frontend = "build[uv]"
test-command = "pytest {project}/tests/unit"
test-groups = ["test-unit"] # uv pip install --group test-unit

[tool.cibuildwheel.pyodide]
build = "cp314-*"
# https://cibuildwheel.pypa.io/en/stable/platforms/#pyodide
test-command = "python -m pytest {project}/tests/unit"

[tool.cibuildwheel.linux]
archs = [
    "x86_64",
    "i686",
    "aarch64",
    "ppc64le",
    "s390x",
    "armv7l",
    "riscv64",
]

[tool.cibuildwheel.macos]
archs = [
    "x86_64",
    "arm64",
    "universal2",
]

[tool.cibuildwheel.windows]
archs = [
    "AMD64",
    "x86",
    "ARM64",
]

[[tool.cibuildwheel.overrides]]
# uv is not available in these images
#
# See:
# * https://github.com/astral-sh/uv/issues/10883
# * https://github.com/astral-sh/uv/issues/17764
build-frontend = "build"
select = "*-musllinux_{ppc64le,s390x,riscv64}"
